version: "3.9"
services:
  web:
    image: nginx:stable-alpine
    ports:
      - 8000:8000
    volumes:
      - ./web/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./web/www:/usr/share/nginx/html
    environment:
      - PORT=8000
      - KC_BASE_URL=http://localhost:8080
      - KC_CLIENT_ID=webapp
      - KC_REALM=example.com
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/initial-realm.json:/opt/keycloak/data/import/realm.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=secret
      - REALM_NAME=example.com
      - REALM_FIRST_USER=mustermann
      - REALM_FIRST_USER_PASSWORD=secret
      - REALM_FIRST_USER_EMAIL=max.mustermann@example.com
      - REALM_FIRST_USER_FIRST_NAME=Max
      - REALM_FIRST_USER_LAST_NAME=Mustermann
      - WEB_CLIENT_ID=webapp
      - WEB_CLIENT_URL=http://localhost:8000
    command: 
      - start-dev --import-realm
