version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    ports:
      - 8080:8080
    volumes:
      - ./keycloak/initial-realm.json:/opt/keycloak/data/import/realm.json
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=secret
      - REALM_NAME=example.com
      - REALM_FIRST_USER=mustermann
      - REALM_FIRST_USER_PASSWORD=secret
      - REALM_FIRST_USER_EMAIL=max.mustermann@example.com
      - REALM_FIRST_USER_FIRST_NAME=Max
      - REALM_FIRST_USER_LAST_NAME=Mustermann
    command: 
      - start-dev --import-realm
